services:
  api:
    build: .
    depends_on:
      - postgres
    # entrypoint: fastapi run app/main.py
    entrypoint: bash -c "/opt/api/db/init_db.sh && sleep infinity"
    # environment:
    #   - DEBUG=1
    image: bowl:api
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/api

  postgres:
    environment:
      - POSTGRES_DB=bowling_events
      - POSTGRES_PASSWORD=bowl123
      - POSTGRES_USER=bowler
#       - "POSTGRES_HOST_AUTH_METHOD=trust"
    image: postgres:17.5-bookworm
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
